driver=org.postgresql.Driver
url=jdbc:postgresql://localhost:5432/clinic_db
username= knight05
password= Knight@85%Fury
liquibase.hub.mode=off
databaseChangeLogLockTableName=t_database_changelog_lock
databaseChangeLogTableName=t_database_changelog
